<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>xiaoxu_music_bridge</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <UseWinRT>true</UseWinRT>
  </PropertyGroup>

</Project>
